// 30 daily scam/safety tips — rotated one per day (day of year % 30)

export const DAILY_SHIELD_TIPS = [
  "If someone calls asking for your Medicare number, hang up. Real Medicare never calls you first.",
  "Got a text saying your Amazon order has a problem? Don't click the link. Go to Amazon directly.",
  "Scammers can now clone a family member's voice using AI. If someone calls asking for money, hang up and call them back at their real number.",
  "No real company will ever ask you to pay with gift cards. That's always a scam.",
  "If a pop-up says your computer has a virus and gives a number to call — close the window. It's a scam.",
  "The IRS will never call you demanding immediate payment. They always send a letter first.",
  "If someone you met online asks for money, stop and talk to a family member first. Romance scams are very common.",
  "Never share your Social Security number over the phone unless you initiated the call to a number you trust.",
  "\"You've won a prize!\" messages that ask for a fee are always scams. Real prizes never cost money to claim.",
  "If your bank calls asking for your password or PIN, hang up. Your bank already has your information.",
  "Be careful with emails that say \"Your account has been compromised.\" Go to the website directly — don't click email links.",
  "Fake charity calls increase after natural disasters. Give only to charities you know and trust.",
  "If a caller says your grandchild is in jail and needs bail money, hang up and call your grandchild directly.",
  "Free trial offers that ask for your credit card often charge you later. Read the fine print or skip it.",
  "Door-to-door salespeople offering \"free\" home inspections may be scoping your home. Ask for ID and a business card.",
  "If someone pressures you to decide RIGHT NOW, that's a red flag. Legitimate offers give you time to think.",
  "Miracle cure ads for health products are almost always misleading. Check with your doctor first.",
  "Never give remote access to your computer to someone who called you. Tech support doesn't call you first.",
  "Check your bank and credit card statements regularly. Report any charges you don't recognize.",
  "If an email looks like it's from a friend but asks for money or gift cards, their account may be hacked. Call them.",
  "Social media quizzes that ask for your mother's maiden name or first pet are harvesting security answers.",
  "Utility companies will never threaten to shut off your power unless you pay immediately with a gift card.",
  "Be wary of online ads for products at prices that seem too good to be true. They usually are.",
  "If someone asks you to deposit a check and send part of the money back, it's a fake check scam.",
  "Government agencies will never ask for payment via cryptocurrency or wire transfer.",
  "Before hiring any home repair service, get at least two written estimates and check online reviews.",
  "If a website URL starts with \"http\" instead of \"https\", don't enter any personal information.",
  "Scammers sometimes leave voicemails that sound urgent. Don't call back unfamiliar numbers — look up the real number instead.",
  "Keep your phone and computer software updated. Updates often fix security problems that scammers exploit.",
  "When in doubt about any call, text, or email — ask a family member or friend before taking action.",
];
